### ISSUE TITLE
ApplicationScanStatus enum validation error

### ISSUE THREAD

**Issue by NicolasMugnier** [mission-apprentissage/labonnealternance#1382]
Bonjour,

depuis hier toutes les soumissions de candidatures que nous envoyons sur l'url [https://labonnealternance.apprentissage.beta.gouv.fr/api/v1/application](https://labonnealternance.apprentissage.beta.gouv.fr/api/v1/application) sont en erreur.

L'erreur remontée par l'API est la suivante : 

```json
{"data":{"validationError":{"issues":[{"expected":"'WAITING_FOR_SCAN' | 'VIRUS_DETECTED' | 'ERROR_CLAMAV' | 'NO_VIRUS_DETECTED'","received":"undefined","code":"invalid_type","path":["scan_status"],"message":"'waiting_for_scan' | 'virus_detected' | 'error_clamav' | 'no_virus_detected' attendu"}],"name":"ZodError","statusCode":400,"code":"FST_ERR_VALIDATION","validationContext":"body"}},"message":"body.scan_status: 'waiting_for_scan' | 'virus_detected' | 'error_clamav' | 'no_virus_detected' attendu","error":"Bad Request","statusCode":400}
```
Je pense que ce bug a été introduit suite à ce [commit](https://github.com/mission-apprentissage/labonnealternance/commit/8f34efd78f1bed020364b6a3bdcb32a915b92c72) 

Il semble que l'attribut `scan_status` ai été rajouté comme requis dans le payload du `POST /v1/application` : 

<img width="400"  alt="Screenshot 2024-07-26 at 14 12 39" src="https://github.com/user-attachments/assets/f76021f1-0ddc-4190-9e5a-30be8e4d4504">

<img width="400" alt="Screenshot 2024-07-26 at 14 13 26" src="https://github.com/user-attachments/assets/d33a5191-5058-4613-bad3-e894afc9a6d8">

Est-ce que ceci est volontaire ou un effet de bord lié à l'ajout de l'enum concernant les différents états du scan de sécurité ?

**Comment by moroine** [comment]
@NicolasMugnier c'est deployé en production

**Comment by NicolasMugnier** [comment]
Merci beaucoup @moroine ! Les calls sont bien OK !
